### ISSUE TITLE
Installation fails on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by minghao912** [BYVoid/OpenCC#544]
Hi, I'm having basically the same problem as issue #399, only mine hangs at an earlier point. I've tried the solutions others have mentioned, with no results - it gives the same error.

I am installing OpenCC via `npm i opencc` and `npm i opencc@1.0.6`

-- System Information --
OS: Ubuntu 20.04.1 LTS
GCC: 9.3.0
Node: 14.5.1
OpenCC: 1.1.1, 1.0.6

If anyone has any ideas of how I could solve this, please help! Let me know if any other information is needed. I'm still new to web development so please be kind with me!

-- Console Log --
```
root@dragonfruit:/var/www/html/node# npm i opencc --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'opencc', '--verbose' ]
npm info using npm@6.14.8
npm info using node@v14.15.1
npm verb npm-session 72db646d0a566cd2
npm http fetch GET 304 https://registry.npmjs.org/opencc 120ms (from cache)
npm timing stage:loadCurrentTree Completed in 511ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 3ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 197ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 136ms
npm timing stage:loadIdealTree Completed in 463ms
npm timing stage:generateActionsToTake Completed in 15ms
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-fc91b9cecde9c59c.lock for /var/www/html/node/node_modules/.staging
npm timing audit submit Completed in 83ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 84ms
npm timing audit body Completed in 2ms
npm timing action:extract Completed in 258ms
npm info lifecycle opencc@1.1.1~preuninstall: opencc@1.1.1
npm info lifecycle opencc@1.1.1~uninstall: opencc@1.1.1
npm verb unbuild rmStuff opencc@1.1.1 from /var/www/html/node/node_modules
npm info lifecycle opencc@1.1.1~postuninstall: opencc@1.1.1
npm timing action:unbuild Completed in 7ms
npm timing action:remove Completed in 84ms
npm timing action:finalize Completed in 3ms
npm timing action:refresh-package-json Completed in 9ms
npm info lifecycle opencc@1.1.1~preinstall: opencc@1.1.1
npm timing action:preinstall Completed in 2ms
npm info linkStuff opencc@1.1.1
npm timing action:build Completed in 2ms
npm info lifecycle opencc@1.1.1~install: opencc@1.1.1

> opencc@1.1.1 install /var/www/html/node/node_modules/opencc
> node-pre-gyp install --fallback-to-build || node-pre-gyp rebuild

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   '/usr/bin/node',
node-pre-gyp verb cli   '/var/www/html/node/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@14.15.1 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "/var/www/html/node/node_modules/opencc/build/Release/opencc.node" (not found)
node-pre-gyp http GET https://github.com/BYVoid/OpenCC/releases/download/1.1.1/opencc-v1.1.1-node-v83-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/BYVoid/OpenCC/releases/download/1.1.1/opencc-v1.1.1-node-v83-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/BYVoid/OpenCC/releases/download/1.1.1/opencc-v1.1.1-node-v83-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for opencc@1.1.1 and node@14.15.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/BYVoid/OpenCC/releases/download/1.1.1/opencc-v1.1.1-node-v83-linux-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'clean'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.15.1 | linux | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/var/www/html/node/node_modules/opencc/build/Release/opencc.node',
gyp verb cli   '--module_name=opencc',
gyp verb cli   '--module_path=/var/www/html/node/node_modules/opencc/build/Release',
gyp verb cli   '--napi_version=7',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v83'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.15.1 | linux | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - "python2" is not in PATH or produced an error
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.8.5"
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 14.15.1
gyp verb command install [ '14.15.1' ]
gyp verb install input version string "14.15.1"
gyp verb install installing version: 14.15.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.15.1
gyp verb build dir attempting to create "build" dir: /var/www/html/node/node_modules/opencc/build
gyp verb build dir "build" dir needed to be created? /var/www/html/node/node_modules/opencc/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /var/www/html/node/node_modules/opencc/build/config.gypi
gyp verb config.gypi checking for gypi file: /var/www/html/node/node_modules/opencc/config.gypi
gyp verb common.gypi checking for gypi file: /var/www/html/node/node_modules/opencc/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/html/node/node_modules/opencc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/14.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/html/node/node_modules/opencc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'build',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/var/www/html/node/node_modules/opencc/build/Release/opencc.node',
gyp verb cli   '--module_name=opencc',
gyp verb cli   '--module_path=/var/www/html/node/node_modules/opencc/build/Release',
gyp verb cli   '--napi_version=7',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v83'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.15.1 | linux | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /root/.cache/node-gyp/14.15.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/www/html/node/node_modules/opencc/build'
  rm -rf "Release/s2t.json" && cp -af "../data/config/s2t.json" "Release/s2t.json"
  rm -rf "Release/t2s.json" && cp -af "../data/config/t2s.json" "Release/t2s.json"
  rm -rf "Release/s2tw.json" && cp -af "../data/config/s2tw.json" "Release/s2tw.json"
  rm -rf "Release/s2twp.json" && cp -af "../data/config/s2twp.json" "Release/s2twp.json"
  rm -rf "Release/tw2s.json" && cp -af "../data/config/tw2s.json" "Release/tw2s.json"
  rm -rf "Release/tw2sp.json" && cp -af "../data/config/tw2sp.json" "Release/tw2sp.json"
  rm -rf "Release/t2tw.json" && cp -af "../data/config/t2tw.json" "Release/t2tw.json"
  rm -rf "Release/s2hk.json" && cp -af "../data/config/s2hk.json" "Release/s2hk.json"
  rm -rf "Release/hk2s.json" && cp -af "../data/config/hk2s.json" "Release/hk2s.json"
  rm -rf "Release/t2hk.json" && cp -af "../data/config/t2hk.json" "Release/t2hk.json"
  rm -rf "Release/t2jp.json" && cp -af "../data/config/t2jp.json" "Release/t2jp.json"
  rm -rf "Release/jp2t.json" && cp -af "../data/config/jp2t.json" "Release/jp2t.json"
  touch Release/obj.target/configs.stamp
  g++ '-DNODE_GYP_MODULE_NAME=opencc' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-DVERSION="1.1.1"' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/root/.cache/node-gyp/14.15.1/include/node -I/root/.cache/node-gyp/14.15.1/src -I/root/.cache/node-gyp/14.15.1/deps/openssl/config -I/root/.cache/node-gyp/14.15.1/deps/openssl/openssl/include -I/root/.cache/node-gyp/14.15.1/deps/uv/include -I/root/.cache/node-gyp/14.15.1/deps/zlib -I/root/.cache/node-gyp/14.15.1/deps/v8/include -I../src -I../deps/rapidjson-1.1.0 -I../deps/marisa-0.2.5/include -I../deps/marisa-0.2.5/lib -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -std=c++0x -O3 -fno-omit-frame-pointer -fno-rtti -std=gnu++1y -MMD -MF ./Release/.deps/Release/obj.target/opencc/node/marisa.o.d.raw   -c -o Release/obj.target/opencc/node/marisa.o ../node/marisa.cc
In file included from ../node/marisa.cc:13:
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc: In member function ‘void marisa::grimoire::vector::BitVector::build_index(const marisa::grimoire::vector::BitVector&, bool, bool)’:
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:785:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
  785 |         ranks_[rank_id].set_rel1(num_1s - ranks_[rank_id].abs());
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:787:7: note: here
  787 |       case 1: {
      |       ^~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:788:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
  788 |         ranks_[rank_id].set_rel2(num_1s - ranks_[rank_id].abs());
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:790:7: note: here
  790 |       case 2: {
      |       ^~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:791:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
  791 |         ranks_[rank_id].set_rel3(num_1s - ranks_[rank_id].abs());
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:793:7: note: here
  793 |       case 3: {
      |       ^~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:794:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
  794 |         ranks_[rank_id].set_rel4(num_1s - ranks_[rank_id].abs());
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:796:7: note: here
  796 |       case 4: {
      |       ^~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:797:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
  797 |         ranks_[rank_id].set_rel5(num_1s - ranks_[rank_id].abs());
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:799:7: note: here
  799 |       case 5: {
      |       ^~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:800:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
  800 |         ranks_[rank_id].set_rel6(num_1s - ranks_[rank_id].abs());
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/marisa-0.2.5/lib/marisa/grimoire/vector/bit-vector.cc:802:7: note: here
  802 |       case 6: {
      |       ^~~~
  g++ '-DNODE_GYP_MODULE_NAME=opencc' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-DVERSION="1.1.1"' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/root/.cache/node-gyp/14.15.1/include/node -I/root/.cache/node-gyp/14.15.1/src -I/root/.cache/node-gyp/14.15.1/deps/openssl/config -I/root/.cache/node-gyp/14.15.1/deps/openssl/openssl/include -I/root/.cache/node-gyp/14.15.1/deps/uv/include -I/root/.cache/node-gyp/14.15.1/deps/zlib -I/root/.cache/node-gyp/14.15.1/deps/v8/include -I../src -I../deps/rapidjson-1.1.0 -I../deps/marisa-0.2.5/include -I../deps/marisa-0.2.5/lib -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -std=c++0x -O3 -fno-omit-frame-pointer -fno-rtti -std=gnu++1y -MMD -MF ./Release/.deps/Release/obj.target/opencc/node/opencc.o.d.raw   -c -o Release/obj.target/opencc/node/opencc.o ../node/opencc.cc
../node/opencc.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE OpenccBinding::Convert(Nan::NAN_METHOD_ARGS_TYPE)’:
../node/opencc.cc:94:37: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   94 |                   (uv_after_work_cb)AfterConvert);
      |                                     ^~~~~~~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../node/opencc.cc:2:
../node/opencc.cc: At global scope:
/root/.cache/node-gyp/14.15.1/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/14.15.1/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../node/opencc.cc:184:1: note: in expansion of macro ‘NODE_MODULE’
  184 | NODE_MODULE(binding, OpenccBinding::Init);
      | ^~~~~~~~~~~
In file included from ../src/Config.cpp:23,
                 from ../node/opencc.cc:9:
../deps/rapidjson-1.1.0/document.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator>::SetObjectRaw(rapidjson::GenericValue<Encoding, Allocator>::Member*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::Member = rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >; rapidjson::SizeType = unsigned int]’:
../deps/rapidjson-1.1.0/document.h:2363:9:   required from ‘bool rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::EndObject(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator; rapidjson::SizeType = unsigned int]’
../deps/rapidjson-1.1.0/reader.h:1736:18:   required from ‘rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Transit(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/reader.h:1832:35:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/reader.h:487:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/document.h:2159:22:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; SourceEncoding = rapidjson::UTF8<>; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/document.h:2175:65:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/document.h:2200:60:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with unsigned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
../src/Config.cpp:242:53:   required from here
../deps/rapidjson-1.1.0/document.h:1952:24: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ {aka ‘struct rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >’} with no trivial copy-assignment; use copy-assignment instead [-Wclass-memaccess]
 1952 |             std::memcpy(m, members, count * sizeof(Member));
      |             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/Config.cpp:23,
                 from ../node/opencc.cc:9:
../deps/rapidjson-1.1.0/document.h:71:8: note: ‘rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ {aka ‘struct rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >’} declared here
   71 | struct GenericMember {
      |        ^~~~~~~~~~~~~
In file included from ../src/Config.cpp:23,
                 from ../node/opencc.cc:9:
../deps/rapidjson-1.1.0/document.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator>::SetArrayRaw(rapidjson::GenericValue<Encoding, Allocator>*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]’:
../deps/rapidjson-1.1.0/document.h:2371:9:   required from ‘bool rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::EndArray(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator; rapidjson::SizeType = unsigned int]’
../deps/rapidjson-1.1.0/reader.h:1766:18:   required from ‘rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Transit(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/reader.h:1832:35:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/reader.h:487:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/document.h:2159:22:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; SourceEncoding = rapidjson::UTF8<>; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/document.h:2175:65:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator]’
../deps/rapidjson-1.1.0/document.h:2200:60:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with unsigned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = rapidjson::CrtAllocator; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
../src/Config.cpp:242:53:   required from here
../deps/rapidjson-1.1.0/document.h:1939:24: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
 1939 |             std::memcpy(e, values, count * sizeof(GenericValue));
      |             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/rapidjson-1.1.0/document.h:540:7: note: ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ declared here
  540 | class GenericValue {
      |       ^~~~~~~~~~~~
^Cmake: *** [opencc.target.mk:122: Release/obj.target/opencc/node/opencc.o] Interrupt
npm verb lifecycle opencc@1.1.1~install: unsafe-perm in lifecycle false
npm verb lifecycle opencc@1.1.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/node/node_modules/opencc/node_modules/.bin:/var/www/html/node/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle opencc@1.1.1~install: CWD: /var/www/html/node/node_modules/opencc

root@dragonfruit:/var/www/html/node# ^C
root@dragonfruit:/var/www/html/node# ^C
root@dragonfruit:/var/www/html/node# npm i opencc@1.0.6

> opencc@1.0.6 install /var/www/html/node/node_modules/opencc
> node-pre-gyp install --fallback-to-build || node-pre-gyp rebuild

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/BYVoid/OpenCC/releases/download/1.0.6/opencc-v1.0.6-node-v83-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for opencc@1.0.6 and node@14.15.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/var/www/html/node/node_modules/opencc/build'
  COPY Release/s2t.json
  COPY Release/t2s.json
  COPY Release/s2tw.json
  COPY Release/s2twp.json
  COPY Release/tw2s.json
  COPY Release/tw2sp.json
  COPY Release/t2tw.json
  COPY Release/s2hk.json
  COPY Release/hk2s.json
  COPY Release/t2hk.json
  COPY Release/t2jp.json
  COPY Release/jp2t.json
  TOUCH Release/obj.target/configs.stamp
  CXX(target) Release/obj.target/opencc/node/opencc.o
../node/opencc.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE OpenccBinding::Convert(Nan::NAN_METHOD_ARGS_TYPE)’:
../node/opencc.cc:94:72: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   94 |     uv_queue_work(uv_default_loop(), req, DoConvert, (uv_after_work_cb)AfterConvert);
      |                                                                        ^~~~~~~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../node/opencc.cc:2:
../node/opencc.cc: At global scope:
/root/.cache/node-gyp/14.15.1/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/14.15.1/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../node/opencc.cc:183:1: note: in expansion of macro ‘NODE_MODULE’
  183 | NODE_MODULE(binding, OpenccBinding::Init);
      | ^~~~~~~~~~~
In file included from ../src/Config.cpp:29,
                 from ../node/opencc.cc:10:
../deps/rapidjson-0.11/document.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator>::SetObjectRaw(rapidjson::GenericValue<Encoding, Allocator>::Member*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]’:
../deps/rapidjson-0.11/document.h:789:3:   required from ‘void rapidjson::GenericDocument<Encoding, Allocator>::EndObject(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]’
../deps/rapidjson-0.11/reader.h:271:4:   required from ‘void rapidjson::GenericReader<Encoding, Allocator>::ParseObject(Stream&, Handler&) [with unsigned int parseFlags = 1; Stream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]’
../deps/rapidjson-0.11/reader.h:243:15:   required from ‘bool rapidjson::GenericReader<Encoding, Allocator>::Parse(Stream&, Handler&) [with unsigned int parseFlags = 1; Stream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]’
../deps/rapidjson-0.11/document.h:712:3:   required from ‘rapidjson::GenericDocument<Encoding, Allocator>& rapidjson::GenericDocument<Encoding, Allocator>::ParseStream(Stream&) [with unsigned int parseFlags = 1; Stream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]’
../deps/rapidjson-0.11/document.h:734:54:   required from ‘rapidjson::GenericDocument<Encoding, Allocator>& rapidjson::GenericDocument<Encoding, Allocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator>::Ch*) [with unsigned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericDocument<Encoding, Allocator>::Ch = char]’
../src/Config.cpp:220:53:   required from here
../deps/rapidjson-0.11/document.h:645:9: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  645 |   memcpy(data_.o.members, members, count * sizeof(Member));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/Config.cpp:29,
                 from ../node/opencc.cc:10:
../deps/rapidjson-0.11/document.h:33:9: note: ‘struct rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ declared here
   33 |  struct Member {
      |         ^~~~~~
In file included from ../src/Config.cpp:29,
                 from ../node/opencc.cc:10:
../deps/rapidjson-0.11/document.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator>::SetArrayRaw(rapidjson::GenericValue<Encoding, Allocator>*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]’:
../deps/rapidjson-0.11/document.h:796:3:   required from ‘void rapidjson::GenericDocument<Encoding, Allocator>::EndArray(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]’
../deps/rapidjson-0.11/reader.h:313:4:   required from ‘void rapidjson::GenericReader<Encoding, Allocator>::ParseArray(Stream&, Handler&) [with unsigned int parseFlags = 1; Stream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]’
../deps/rapidjson-0.11/reader.h:244:15:   required from ‘bool rapidjson::GenericReader<Encoding, Allocator>::Parse(Stream&, Handler&) [with unsigned int parseFlags = 1; Stream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]’
../deps/rapidjson-0.11/document.h:712:3:   required from ‘rapidjson::GenericDocument<Encoding, Allocator>& rapidjson::GenericDocument<Encoding, Allocator>::ParseStream(Stream&) [with unsigned int parseFlags = 1; Stream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]’
../deps/rapidjson-0.11/document.h:734:54:   required from ‘rapidjson::GenericDocument<Encoding, Allocator>& rapidjson::GenericDocument<Encoding, Allocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator>::Ch*) [with unsigned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericDocument<Encoding, Allocator>::Ch = char]’
../src/Config.cpp:220:53:   required from here
../deps/rapidjson-0.11/document.h:637:9: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  637 |   memcpy(data_.a.elements, values, count * sizeof(GenericValue));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/Config.cpp:29,
                 from ../node/opencc.cc:10:
../deps/rapidjson-0.11/document.h:30:7: note: ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ declared here
   30 | class GenericValue {
      |       ^~~~~~~~~~~~
^Cmake: *** [opencc.target.mk:119: Release/obj.target/opencc/node/opencc.o] Interrupt

```

_Originally posted by @minghao912 in https://github.com/BYVoid/OpenCC/issues/399#issuecomment-744035540_

**Comment by allencch** [comment]
I have similar issue.

Environment:
Arch Linux
GCC 10.2.0
Node 14.15.3

On the project `RSSHub`, downgrade opencc to 1.0.6 with `yarn add opencc@1.0.6` will successful install the modules.

**Comment by SiqingYu** [comment]
Same issue. @allencch 's solution works for me.

Environment:
Debian GNU/Linux 10 (buster)
Node: v10.23.1
GCC: version 8.3.0 (Debian 8.3.0-6)

**Comment by BYVoid** [comment]
Please try again, as I upgraded marisa-trie.

**Comment by allencch** [comment]
@BYVoid , I tried `git clone` this project, then run `make -d`. It gets the error

```
make[3]: Entering directory '/home/user/OpenCC/build/rel'
Putting child 0x55d437ce4060 (data/STPhrases.ocd2) PID 57102 on the chain.
Live child 0x55d437ce4060 (data/STPhrases.ocd2) PID 57102 
[ 66%] Building STPhrases.ocd2
Reaping winning child 0x55d437ce4060 PID 57102 
Live child 0x55d437ce4060 (data/STPhrases.ocd2) PID 57103 
Reaping losing child 0x55d437ce4060 PID 57103 
make[3]: *** [data/CMakeFiles/Dictionaries.dir/build.make:101: data/STPhrases.ocd2] Segmentation fault (core dumped)
```

GCC version 10.2.0
OS: Arch Linux

I also tried to `make` with `clang` (version 11.1.0). No issue for `clang`.

**Comment by BYVoid** [comment]
According to https://github.com/BYVoid/OpenCC/issues/533 and https://github.com/s-yata/marisa-trie/issues/35, it looks like a problem of `CXXFLAGS="-O3"`. Please try to build with `-O2`.

**Comment by BYVoid** [comment]
Closed this issue because it is a bug of gcc, and it's fixed on gcc-10 branch.

**Comment by Arfrever** [comment]
[Problem](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97236) was fixed in GCC 10 branch:
[GCC commit 1ab88985631dd2c5a5e3b5c0dce47cf8b6ed2f82](https://gcc.gnu.org/g:1ab88985631dd2c5a5e3b5c0dce47cf8b6ed2f82)
Fix will be released in GCC 10.3.0.

In the meantime, users of various distributions can ask maintainers of GCC in their distributions to backport this fix.

**Comment by Keith-Hon** [comment]
gcc 10.3.0
ubuntu 20.04.3 LTS
node: v16.13.0
opencc: 1.1.3

problem still persists
